### ISSUE TITLE
Todos

### ISSUE THREAD

**Issue by devhik0** [invincibleinventor/evoltwebs#2]
- Merge PR to apply some lint and format rules.
- Fix all lint issues and edit code according to that
- Arrange app to show public posts at first open before login, put login logic to navbar to make it optional
- Add email login as first auth option, keep OAuth as an alternative.

**Comment by invincibleinventor** [comment]
- Merged PR
- Fixed Lint Issues
- Feature Request Put On Hold Temporarily
- Added Email Login Along With OAuth
